create table convert.lips_log_focus
(
    equipment_name            text      not null,
    log_time                  timestamp not null,
    device                    text,
    process                   text,
    bl                        real,
    bc                        real,
    br                        real,
    fl                        real,
    fc                        real,
    fr                        real,
    left_vt                   real,
    left_hs                   real,
    right_vt                  real,
    right_hs                  real,
    center_vt                 real,
    center_hs                 real,
    z                         real,
    pitch                     real,
    roll                      real,
    mark                      text,
    glass_id                  text,
    lot_id                    text,
    left_hv_base_difference   real,
    right_hv_base_difference  real,
    center_hv_base_difference real,
    left_st_base_difference   real,
    right_st_base_difference  real,
    center_st_base_difference real,
    ill_mode                  text,
    log_idx                   integer   not null,
    created_time              timestamp not null,
    request_id              varchar(50),
    constraint lips_log_focus_pkey
        primary key (equipment_name, log_time, log_idx, device, process, request_id)
);
