create table convert.plate_auto_focus_compensation
(
    equipment_name            text      not null,
    device                    text,
    process                   text,
    chuck                     text,
    plate_no                  integer,
    step_no                   integer,
    glass_id                  text,
    lot_id                    text,
    log_time                  timestamp not null,
    stage_pos_afc_meas_z2     integer,
    stage_pos_afc_meas_z3     integer,
    stage_pos_afc_meas_roll   integer,
    stage_pos_afc_meas_z1     integer,
    stage_pos_afc_meas_height integer,
    stage_pos_afc_meas_pitch  integer,
    chuck_pos_afc_meas_pitch  integer,
    chuck_pos_afc_meas_roll   integer,
    mask_bend_roll            integer,
    chuck_pos_afc_meas_height integer,
    mask_bend_height          integer,
    mask_bend_pitch           integer,
    drive_roll                integer,
    lips_height               integer,
    drive_height              integer,
    drive_pitch               integer,
    zsens_bc                  integer,
    zsens_br                  integer,
    zsens_fr                  integer,
    zsens_bl                  integer,
    zsens_fl                  integer,
    zsens_fc                  integer,
    stage_pos_afc_meas_z4     integer,
    log_idx                   integer   not null,
    created_time              timestamp not null,
    request_id              varchar(50),
    constraint plate_auto_focus_compensation_pkey
        primary key (equipment_name, log_time, log_idx, device, process, request_id)
);
