create table convert.mount_press_log
(
    equipment_name   text      not null,
    status           text,
    z_cnt_rb         integer,
    z_cnt_lb         integer,
    z_cnt_lf         integer,
    z_cnt_rf         integer,
    z_out_rb_bit     real,
    z_out_lb_bit     real,
    z_out_lf_bit     real,
    z_out_rf_bit     real,
    z_cur_rb_bit     real,
    z_cur_lb_bit     real,
    z_cur_lf_bit     real,
    z_cur_rf_bit     real,
    psx_nm           real,
    psy_nm           real,
    pst_msec         real,
    psz_nm           real,
    psp_msec         real,
    psr_msec         real,
    msy_nm           real,
    log_time         timestamp not null,
    rb_mm            integer,
    rf_mm            integer,
    lb_mm            integer,
    lf_mm            integer,
    rb_kpa           integer,
    rf_kpa           integer,
    lb_kpa           integer,
    lf_kpa           integer,
    log_idx          integer   not null,
    mnt_cout_rbz_bit integer,
    mnt_cout_lbz_bit integer,
    mnt_cout_lfz_bit integer,
    mnt_cout_rfz_bit integer,
    created_time     timestamp not null,
    request_id              varchar(50),
    constraint mount_press_log_pkey
        primary key (equipment_name, log_time, log_idx, request_id)
);