create table convert.pre_scan_compensation_monitor
(
    equipment_name          text      not null,
    log_idx                 integer   not null,
    log_time                timestamp not null,
    device                  text,
    process                 text,
    plate_no                integer,
    step_no                 integer,
    glass_id                text,
    lot_id                  text,
    chuck                   text,
    expo_start_pos_psy      real,
    expo_start_pos_psz      real,
    expo_start_pos_psr      real,
    expo_start_pos_psp      real,
    expo_end_pos_psy        real,
    expo_end_pos_psz        real,
    expo_end_pos_psr        real,
    expo_end_pos_psp        real,
    psz_comp_start_pos1_psy real,
    psz_comp_start_pos1_psz real,
    psz_comp_start_pos2_psy real,
    psz_comp_start_pos2_psz real,
    psr_comp_start_pos1_psy real,
    psr_comp_start_pos1_psr real,
    psr_comp_start_pos2_psy real,
    psr_comp_start_pos2_psr real,
    psp_comp_start_pos1_psy real,
    psp_comp_start_pos1_psp real,
    psp_comp_start_pos2_psy real,
    psp_comp_start_pos2_psp real,
    psz_maxdiff_psy         real,
    psz_maxdiff_psz         real,
    psr_maxdiff_psy         real,
    psr_maxdiff_psr         real,
    psp_maxdiff_psy         real,
    psp_maxdiff_psp         real,
    mp_offset               real,
    created_time            timestamp,
    request_id              varchar(50),
    constraint pre_scan_compensation_monitor_pk
        primary key (equipment_name, log_idx, log_time, device, process, request_id)
);
